#!/bin/sh
#
# This script creates the tar ball test.tgz, which
# contains all necessary testing programs and data
# for testing. Before doing a "cvs commit" one should
# compile with test.f90 and run the test suit. If the
# test suit changes, then modify and run this script 
# to create an updated tar ball test.tgz. 
#

tar zcvf docs.tgz doc_make dedx rate acoeff references misc mathematica A_asymptotic_doc_1 A_asymptotic_doc_2
